import {BookGenre} from "../model/book/bookGenre";


export const GenreIcon: Record<BookGenre, string> = {
	[BookGenre.FICTION]: "menu_book",
	[BookGenre.NON_FICTION]: "newspaper",
	[BookGenre.MYSTERY]: "person_search",
	[BookGenre.THRILLER]: "directions_run",
	[BookGenre.ROMANCE]: "favorite",
	[BookGenre.SCIENCE_FICTION]: "psychology_alt",
	[BookGenre.FANTASY]: "auto_fix_high",
	[BookGenre.HORROR]: "mood_bad",
	[BookGenre.HISTORICAL_FICTION]: "history_edu",
	[BookGenre.BIOGRAPHY]: "person",
	[BookGenre.SELF_HELP]: "healing",
	[BookGenre.YOUNG_ADULT]: "local_play",
	[BookGenre.DYSTOPIAN]: "public",
	[BookGenre.ACTION_ADVENTURE]: "directions_run",
	[BookGenre.SUSPENSE]: "person_search",
	[BookGenre.CONTEMPORARY_FICTION]: "book",
	[BookGenre.LITERARY_FICTION]: "menu_book",
	[BookGenre.MAGIC_REALISM]: "history_edu",
	[BookGenre.SHORT_STORY]: "menu_book",
	[BookGenre.NEW_ADULT]: "diversity_3",
	[BookGenre.CHILDREN]: "child_care",
	[BookGenre.MEMOIR_AUTOBIOGRAPHY]: "person",
	[BookGenre.FOOD_DRINK]: "restaurant",
	[BookGenre.GRAPHIC_NOVEL]: "dashboard",
	[BookGenre.ART_PHOTOGRAPHY]: "photo_camera",
	[BookGenre.HISTORY]: "history_edu",
	[BookGenre.TRAVEL]: "flight",
	[BookGenre.TRUE_CRIME]: "fingerprint",
	[BookGenre.HUMOR]: "mood",
	[BookGenre.ESSAY]: "description",
	[BookGenre.GUIDE]: "list",
	[BookGenre.RELIGION]: "church",
	[BookGenre.SPIRITUALITY]: "self_improvement",
	[BookGenre.HUMANITIES_SOCIAL_SCIENCES]: "groups",
	[BookGenre.PARENTING_FAMILIES]: "family_restroom",
	[BookGenre.SCIENCE_TECHNOLOGY]: "biotech",
};