export enum BookSearchOrderBy {
	PRICE_ASC = "PRICE_ASC",
	PRICE_DESC = "PRICE_DESC",
	PAGE_COUNT_ASC = "PAGE_COUNT_ASC",
	PAGE_COUNT_DESC = "PAGE_COUNT_DESC",
	PUBLICATION_DATE_ASC = "PUBLICATION_DATE_ASC",
	PUBLICATION_DATE_DESC = "PUBLICATION_DATE_DESC",
	BEST_SELLERS = "BEST_SELLERS",
	NEW_DEALS = "NEW_DEALS"
}