export enum BookSearchOrderBy {
	PRICE_ASC = "PRICE ASC",
	PRICE_DESC = "PRICE DESC",
	PAGE_COUNT_ASC = "PAGE COUNT ASC",
	PAGE_COUNT_DESC = "PAGE COUNT DESC",
	PUBLICATION_DATE_ASC = "PUBLICATION DATE ASC",
	PUBLICATION_DATE_DESC = "PUBLICATION DATE DESC",
	BEST_SELLERS = "BEST SELLERS",
	NEW_DEALS = "NEW DEALS"
}